CREATE TYPE "UserRole" AS ENUM ('USER','ADMIN');
CREATE TYPE "Gender" AS ENUM ('WOMAN','MAN','NON_BINARY','OTHER','PREFER_NOT_TO_SAY');
CREATE TYPE "TestType" AS ENUM ('BIG_FIVE','HEXACO','CUSTOM');
CREATE TYPE "QuestionKind" AS ENUM ('LIKERT','SINGLE_CHOICE','MULTIPLE_CHOICE','BOOLEAN','NUMBER','TEXT');
CREATE TYPE "IntegrationProvider" AS ENUM ('SPOTIFY','LETTERBOXD');
CREATE TYPE "IntegrationStatus" AS ENUM ('PENDING','CONNECTED','EXPIRED','ERROR','DISCONNECTED');
CREATE TYPE "AlgorithmKey" AS ENUM ('PERSONALITY','TASTE','LIFESTYLE');
CREATE TYPE "MatchRunStatus" AS ENUM ('PENDING','COMPLETED','FAILED');

CREATE TABLE "users" ("id" UUID NOT NULL,"email" TEXT NOT NULL,"role" "UserRole" NOT NULL DEFAULT 'USER',"display_name" TEXT,"birth_date" DATE,"gender" "Gender","bio" TEXT,"avatar_url" TEXT,"is_discoverable" BOOLEAN NOT NULL DEFAULT true,"onboarding_complete" BOOLEAN NOT NULL DEFAULT false,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "users_pkey" PRIMARY KEY ("id"));
CREATE TABLE "housing_preferences" ("id" UUID NOT NULL,"user_id" UUID NOT NULL,"city" TEXT NOT NULL,"country_code" CHAR(2) NOT NULL,"min_monthly_budget" INTEGER NOT NULL,"max_monthly_budget" INTEGER NOT NULL,"currency" CHAR(3) NOT NULL DEFAULT 'USD',"move_in_date" DATE,"preferred_areas" TEXT[] DEFAULT ARRAY[]::TEXT[],CONSTRAINT "housing_preferences_pkey" PRIMARY KEY ("id"));
CREATE TABLE "lifestyle_profiles" ("id" UUID NOT NULL,"user_id" UUID NOT NULL,"cleanliness" INTEGER NOT NULL,"social_level" INTEGER NOT NULL,"sleep_schedule" INTEGER NOT NULL,"noise_tolerance" INTEGER NOT NULL,"guests_frequency" INTEGER NOT NULL,"smoking_allowed" BOOLEAN NOT NULL DEFAULT false,"pets_allowed" BOOLEAN NOT NULL DEFAULT true,"has_pets" BOOLEAN NOT NULL DEFAULT false,CONSTRAINT "lifestyle_profiles_pkey" PRIMARY KEY ("id"));
CREATE TABLE "test_definitions" ("id" UUID NOT NULL,"slug" TEXT NOT NULL,"name" TEXT NOT NULL,"type" "TestType" NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,"description" TEXT,"is_active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "test_definitions_pkey" PRIMARY KEY ("id"));
CREATE TABLE "questions" ("id" UUID NOT NULL,"test_definition_id" UUID NOT NULL,"code" TEXT NOT NULL,"prompt" TEXT NOT NULL,"kind" "QuestionKind" NOT NULL DEFAULT 'LIKERT',"trait" TEXT NOT NULL,"reverse_scored" BOOLEAN NOT NULL DEFAULT false,"position" INTEGER NOT NULL,"options" JSONB,"min_value" INTEGER,"max_value" INTEGER,"weight" DOUBLE PRECISION NOT NULL DEFAULT 1,CONSTRAINT "questions_pkey" PRIMARY KEY ("id"));
CREATE TABLE "test_attempts" ("id" UUID NOT NULL,"user_id" UUID NOT NULL,"test_definition_id" UUID NOT NULL,"completed_at" TIMESTAMP(3),"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "test_attempts_pkey" PRIMARY KEY ("id"));
CREATE TABLE "test_responses" ("id" UUID NOT NULL,"attempt_id" UUID NOT NULL,"question_id" UUID NOT NULL,"value" JSONB NOT NULL,CONSTRAINT "test_responses_pkey" PRIMARY KEY ("id"));
CREATE TABLE "trait_scores" ("id" UUID NOT NULL,"attempt_id" UUID NOT NULL,"trait" TEXT NOT NULL,"score" DOUBLE PRECISION NOT NULL,CONSTRAINT "trait_scores_pkey" PRIMARY KEY ("id"));
CREATE TABLE "external_integrations" ("id" UUID NOT NULL,"user_id" UUID NOT NULL,"provider" "IntegrationProvider" NOT NULL,"external_user_id" TEXT,"username" TEXT,"access_token_encrypted" TEXT,"refresh_token_encrypted" TEXT,"token_expires_at" TIMESTAMP(3),"status" "IntegrationStatus" NOT NULL DEFAULT 'PENDING',"last_synced_at" TIMESTAMP(3),"metadata" JSONB,CONSTRAINT "external_integrations_pkey" PRIMARY KEY ("id"));
CREATE TABLE "taste_items" ("id" UUID NOT NULL,"user_id" UUID NOT NULL,"provider" "IntegrationProvider" NOT NULL,"external_id" TEXT NOT NULL,"kind" TEXT NOT NULL,"name" TEXT NOT NULL,"artists" TEXT[] DEFAULT ARRAY[]::TEXT[],"genres" TEXT[] DEFAULT ARRAY[]::TEXT[],"score" DOUBLE PRECISION NOT NULL DEFAULT 1,"metadata" JSONB,CONSTRAINT "taste_items_pkey" PRIMARY KEY ("id"));
CREATE TABLE "algorithm_configs" ("id" UUID NOT NULL,"key" "AlgorithmKey" NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT true,"weight" DOUBLE PRECISION NOT NULL DEFAULT 1,"version" TEXT NOT NULL DEFAULT '1.0.0',"settings" JSONB NOT NULL DEFAULT '{}',"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "algorithm_configs_pkey" PRIMARY KEY ("id"));
CREATE TABLE "match_runs" ("id" UUID NOT NULL,"subject_id" UUID NOT NULL,"status" "MatchRunStatus" NOT NULL DEFAULT 'PENDING',"context" JSONB,"error" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "match_runs_pkey" PRIMARY KEY ("id"));
CREATE TABLE "match_results" ("id" UUID NOT NULL,"match_run_id" UUID NOT NULL,"subject_id" UUID NOT NULL,"candidate_id" UUID NOT NULL,"total_score" DOUBLE PRECISION NOT NULL,"rank" INTEGER NOT NULL,"explanation" JSONB,CONSTRAINT "match_results_pkey" PRIMARY KEY ("id"));
CREATE TABLE "match_algorithm_scores" ("id" UUID NOT NULL,"match_result_id" UUID NOT NULL,"algorithm_key" "AlgorithmKey" NOT NULL,"score" DOUBLE PRECISION NOT NULL,"weight" DOUBLE PRECISION NOT NULL,"version" TEXT NOT NULL,"explanation" JSONB,CONSTRAINT "match_algorithm_scores_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX "housing_preferences_user_id_key" ON "housing_preferences"("user_id");
CREATE INDEX "housing_preferences_city_max_monthly_budget_idx" ON "housing_preferences"("city","max_monthly_budget");
CREATE UNIQUE INDEX "lifestyle_profiles_user_id_key" ON "lifestyle_profiles"("user_id");
CREATE UNIQUE INDEX "test_definitions_slug_key" ON "test_definitions"("slug");
CREATE UNIQUE INDEX "test_definitions_type_version_key" ON "test_definitions"("type","version");
CREATE UNIQUE INDEX "questions_test_definition_id_code_key" ON "questions"("test_definition_id","code");
CREATE UNIQUE INDEX "questions_test_definition_id_position_key" ON "questions"("test_definition_id","position");
CREATE INDEX "test_attempts_user_id_completed_at_idx" ON "test_attempts"("user_id","completed_at");
CREATE UNIQUE INDEX "test_responses_attempt_id_question_id_key" ON "test_responses"("attempt_id","question_id");
CREATE UNIQUE INDEX "trait_scores_attempt_id_trait_key" ON "trait_scores"("attempt_id","trait");
CREATE UNIQUE INDEX "external_integrations_user_id_provider_key" ON "external_integrations"("user_id","provider");
CREATE INDEX "taste_items_user_id_provider_idx" ON "taste_items"("user_id","provider");
CREATE UNIQUE INDEX "taste_items_user_id_provider_external_id_kind_key" ON "taste_items"("user_id","provider","external_id","kind");
CREATE UNIQUE INDEX "algorithm_configs_key_key" ON "algorithm_configs"("key");
CREATE INDEX "match_runs_subject_id_created_at_idx" ON "match_runs"("subject_id","created_at");
CREATE INDEX "match_results_subject_id_total_score_idx" ON "match_results"("subject_id","total_score");
CREATE UNIQUE INDEX "match_results_match_run_id_candidate_id_key" ON "match_results"("match_run_id","candidate_id");
CREATE UNIQUE INDEX "match_algorithm_scores_match_result_id_algorithm_key_key" ON "match_algorithm_scores"("match_result_id","algorithm_key");

ALTER TABLE "housing_preferences" ADD CONSTRAINT "housing_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "lifestyle_profiles" ADD CONSTRAINT "lifestyle_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "questions" ADD CONSTRAINT "questions_test_definition_id_fkey" FOREIGN KEY ("test_definition_id") REFERENCES "test_definitions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "test_attempts" ADD CONSTRAINT "test_attempts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "test_attempts" ADD CONSTRAINT "test_attempts_test_definition_id_fkey" FOREIGN KEY ("test_definition_id") REFERENCES "test_definitions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "test_responses" ADD CONSTRAINT "test_responses_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "test_attempts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "test_responses" ADD CONSTRAINT "test_responses_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "trait_scores" ADD CONSTRAINT "trait_scores_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "test_attempts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "external_integrations" ADD CONSTRAINT "external_integrations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "taste_items" ADD CONSTRAINT "taste_items_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "match_runs" ADD CONSTRAINT "match_runs_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "match_results" ADD CONSTRAINT "match_results_match_run_id_fkey" FOREIGN KEY ("match_run_id") REFERENCES "match_runs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "match_results" ADD CONSTRAINT "match_results_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "match_results" ADD CONSTRAINT "match_results_candidate_id_fkey" FOREIGN KEY ("candidate_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "match_algorithm_scores" ADD CONSTRAINT "match_algorithm_scores_match_result_id_fkey" FOREIGN KEY ("match_result_id") REFERENCES "match_results"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "housing_preferences" ADD CONSTRAINT "housing_budget_valid" CHECK ("min_monthly_budget" >= 0 AND "max_monthly_budget" >= "min_monthly_budget");
ALTER TABLE "lifestyle_profiles" ADD CONSTRAINT "lifestyle_scale_valid" CHECK ("cleanliness" BETWEEN 1 AND 5 AND "social_level" BETWEEN 1 AND 5 AND "sleep_schedule" BETWEEN 1 AND 5 AND "noise_tolerance" BETWEEN 1 AND 5 AND "guests_frequency" BETWEEN 1 AND 5);
ALTER TABLE "algorithm_configs" ADD CONSTRAINT "algorithm_weight_valid" CHECK ("weight" >= 0);
ALTER TABLE "match_results" ADD CONSTRAINT "match_total_score_valid" CHECK ("total_score" BETWEEN 0 AND 1);
ALTER TABLE "match_algorithm_scores" ADD CONSTRAINT "algorithm_score_valid" CHECK ("score" BETWEEN 0 AND 1 AND "weight" >= 0);
